### PR TITLE
JOYL-102: implement rolling update

### PR DESCRIPTION
**Pull request by ahmedms**
update dpx.yml for rolling update
still not sure about the api for healthcheck for rest and fluentd services

### CODE REVIEW

**Review by gzaro — COMMENTED** [review]
Please see my comment in jira.

**Comment by ahmedms** [comment]
I added an env variable start_date and it's value is set in the make file so each time the docker starts this value is updated and it triggers all containers to update

**Comment by ahmedms** [comment]
I used configs option to add the configuration file of the fluentd service now if config/fluent.conf is updated then the fluent service will update

**Comment by ahmedms** [comment]
@gzaro can you please check the code now

**Review by gzaro — APPROVED** [review]

**Pull request merged**
